metadata_dir = "/var/lib/garage/meta"
data_dir     = "/var/lib/garage/data"
db_engine    = "sqlite"

replication_factor = 1

[rpc]
bind_addr  = "[::]:3901"
rpc_secret = "7a3c9e1f5d2b8a4c6e0f3b7d9a1c5e8f2b4d6a8c0e2f4b6d8a0c2e4f6b8d0a2"

[s3_api]
s3_region    = "us-east-1"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
admin_token   = "pubtube-garage-test-admin-token"
